# ========== CLUSTER SETUP ==========
#spark.master spark://pyspark-master:7077
spark.ui.port 8080
spark.ui.prometheus.enabled true
spark.sql.streaming.metricsEnabled true

# ========== DYNAMIC ALLOCATION ==========
spark.dynamicAllocation.enabled true
spark.dynamicAllocation.minExecutors 1
spark.shuffle.service.enabled true

# ========== EXECUTOR CONFIGURATION ==========
spark.executor.memory 512m
spark.executor.cores 1
spark.executor.memoryOverhead 1g

# ========== SQL & TIME ==========
spark.sql.session.timeZone Asia/Tehran
spark.sql.adaptive.enabled true
spark.sql.adaptive.coalescePartitions.enabled true
